stages:
  - build
  - package


variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: registry.gitlab.com/$CI_PROJECT_PATH


#####################
# Building
#####################
build-jar:
  stage: build
  image: openjdk:11-oracle
  variables:
    MONGODB_HOST: mongo
    MONGO_INITDB_ROOT_USERNAME: ifunny
    MONGO_INITDB_ROOT_PASSWORD: ifunny
  services:
    - name: mongo
      alias: $MONGO_HOST
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew build
  after_script:
    - cat build/reports/jacoco/test/html/index.html
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
      - build/reports/
      - build/libs/*.jar
    expire_in: 1 week
    when: always
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches



###########################
# Packaging
###########################
package-docker:
  image: docker:stable
  stage: package
  services:
    - docker:stable-dind
  before_script:
    - if [[ ${CI_COMMIT_REF_NAME} == master ]]; then export IMAGE_TAG=latest; else export IMAGE_TAG=${CI_COMMIT_REF_NAME}; fi;
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - master
    - tags
